# fly.toml app configuration file generated for snippetry on 2025-02-03T23:26:24-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'snippetry'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 4567
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
